### ISSUE TITLE
Add a “time_offset”

### ISSUE THREAD

**Issue by dimmanramone** [hasl-platform/lovelace-hasl-departure-card#2]
Requested from @tomoqv

> Add a “time_offset” to take into account the amount of time it takes to reach the station, i.e. if it takes 8 minutes to walk to the train, only show departures from now() + 8 minutes onwards.

> The thing is, that I would like to conserve space in some of my Lovelace views. Showing a number of departures that are impossible to make from my house adds a few lines of information that is of little or no interest to the person looking for the next possible departure. This is a feature request, so I fully understand if it may be low priority.

**Comment by dimmanramone** [comment]
Moved to https://github.com/hasl-platform/lovelace-hasl-departure-card/issues

**Comment by dimmanramone** [comment]
@tomoqv I guess you want it to show the actuall time left and time for the departures but hide the ones you are not able to catch. i.e. It takes 8 minutes from your place to the station and the time is 19:42.
The next departures are 19:47 (5 min), 19:51(9 min), 19:54(12 min). In the card is going to so the actuall times but hide 19:47 because you don't have enough time to catch it.

**Comment by tomoqv** [comment]
Yes, precisely. That way I won't have any superfluous information.

Thanks!
