### ISSUE TITLE
Card doesnt work in HA 106.x

### ISSUE THREAD

**Issue by Pocke01** [hasl-platform/lovelace-hasl-departure-card#8]
Hi, 

After upgrade to HA 106 im getthing these errors on the card:
"Attempted to assign readonly property"  
"Can´t define property "show_cardname": object is not extensible"

Hope its a easy fix!

**Comment by dimmanramone** [comment]
@Pocke01 You are more than welcome to test the version in the dev branch. I will release as soon as in HACS

**Comment by Pocke01** [comment]
The dev branch works!  

Nice work!

**Comment by dimmanramone** [comment]
@Pocke01 Great I'll release it today in the afternoon. Thanks for testing
