### ISSUE TITLE
Problem with tap_action after HA upgrade

### ISSUE THREAD

**Issue by tomoqv** [hasl-platform/lovelace-hasl-departure-card#9]
Hi,
just got a problem with the HASL-card and tap_action after my latest upgrade of HA. This is the lovelace error message:
```
can't define property "tap_action_entity": Object is not extensible

type: 'custom:hasl-departure-card'
show_cardname: false
header: false
departures: true
timeleft: false
updated: false
offset: 5
hide_departed: true
language: sv-SE
entities:
  - sensor.mossens_ip
  - sensor.alleparken
style: |
  ha-card {
    font-size: 1.2em;
    # height: 150px;
    # width: 300px;
    # margin-top: 0px;
    # margin-bottom: 0px;
  }
tap_action: service
service_config:
  domain: browser_mod
  service: popup
  data:
    title: Avgångar
    card:
      type: 'custom:hasl-departure-card'
      header: false
      departures: true
      deviations: true
      timeleft: false
      updated: true
      name: Tidtabeller
      hide_departed: true
      language: sv-SE
      entities:
        - sensor.alleparken
        - sensor.mossens_ip
        - sensor.alviks_strand
        - sensor.alvik
    deviceID:
      - this

```

**Comment by tomoqv** [comment]
I have upgraded to 0.107.6 now. Just noticed that I have not installed HASL departure card through the community store before. Have done that as well. It still doesn't work. Do I need to remove code from my lovelace resources after that?

**Comment by dimmanramone** [comment]
@tomoqv Remove you old card completely, the one that you installed manually. Installl from HACS and make sure that you have the right path under resources. Make sure that you are in the latest browser_mod too. Restart your installation.

**Comment by tomoqv** [comment]
Still doesn't work for me. Ensured browser_mod is lates version in HACS. Removed the js-file from my previous lovelace config and changed the path in ui-lovelace.yaml to:
```
  - url: /local/hasl-departure-card.js
    type: js

```Restarted HA, cleared cache in my browser and pressed "Update" for my Lovelace config in my browsers (firefox and chromium).
Still no cigar...

**Comment by dimmanramone** [comment]
@tomoqv Are you sure the path is right? If you use HACS should look like the following

`- url: /hacsfiles/lovelace-hasl-departure-card/hasl-departure-card.js
    type: js`

**Comment by tomoqv** [comment]
Thank you, now it finally works!
